
import javax.swing.JOptionPane;

public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        publishResultButton = new javax.swing.JButton();
        addNewTeacherInfoButton = new javax.swing.JButton();
        existingInfoButton = new javax.swing.JButton();
        admitStudentButton = new javax.swing.JButton();

        jButton9.setBackground(new java.awt.Color(153, 255, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 0));
        jButton9.setText("Teacher Info");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel.setIcon(new javax.swing.ImageIcon("F:\\Java projects\\Images\\administrator_logo.jpg")); // NOI18N
        imageLabel.setText("jLabel1");

        backButton.setBackground(new java.awt.Color(255, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        publishResultButton.setBackground(new java.awt.Color(153, 255, 153));
        publishResultButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        publishResultButton.setForeground(new java.awt.Color(204, 0, 0));
        publishResultButton.setText("Published Result");
        publishResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishResultButtonActionPerformed(evt);
            }
        });

        addNewTeacherInfoButton.setBackground(new java.awt.Color(153, 255, 153));
        addNewTeacherInfoButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        addNewTeacherInfoButton.setForeground(new java.awt.Color(204, 0, 0));
        addNewTeacherInfoButton.setText("Add Teacher info");
        addNewTeacherInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTeacherInfoButtonActionPerformed(evt);
            }
        });

        existingInfoButton.setBackground(new java.awt.Color(153, 255, 153));
        existingInfoButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        existingInfoButton.setForeground(new java.awt.Color(204, 0, 0));
        existingInfoButton.setText("Existing Info");
        existingInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingInfoButtonActionPerformed(evt);
            }
        });

        admitStudentButton.setBackground(new java.awt.Color(153, 255, 153));
        admitStudentButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        admitStudentButton.setForeground(new java.awt.Color(204, 0, 0));
        admitStudentButton.setText("Admit Student");
        admitStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admitStudentButton)
                .addGap(32, 32, 32)
                .addComponent(publishResultButton)
                .addGap(34, 34, 34)
                .addComponent(addNewTeacherInfoButton)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(existingInfoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(backButton)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admitStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewTeacherInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(existingInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        String value = JOptionPane.showInputDialog("Do you want to Log out?\nPress y to yes\nPress n to no");
        if(value.equals("y") || value.equals("Y")){
            dispose();
            new HomePage().setVisible(true);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void admitStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitStudentButtonActionPerformed
        dispose();
        new AdmitNewStudent().setVisible(true);
    }//GEN-LAST:event_admitStudentButtonActionPerformed

    private void addNewTeacherInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTeacherInfoButtonActionPerformed
        dispose();
        new AddNewTeacherInfo().setVisible(true);
    }//GEN-LAST:event_addNewTeacherInfoButtonActionPerformed

    private void existingInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingInfoButtonActionPerformed
        dispose();
        new ExistingInfo().setVisible(true);
    }//GEN-LAST:event_existingInfoButtonActionPerformed

    private void publishResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishResultButtonActionPerformed
        dispose();
        
        ResultEditable obj = new ResultEditable();
        
        obj.setWhoCall("Admin");
        obj.setVisible(true);
    }//GEN-LAST:event_publishResultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewTeacherInfoButton;
    private javax.swing.JButton admitStudentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton existingInfoButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton publishResultButton;
    // End of variables declaration//GEN-END:variables
}
