

public class ExistingInfo extends javax.swing.JFrame {

    /**
     * Creates new form ExistingInfo
     */
    public ExistingInfo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherInfoButton = new javax.swing.JButton();
        studentInfoButton = new javax.swing.JButton();
        bookShopButton = new javax.swing.JButton();
        libraryButton = new javax.swing.JButton();
        cantinButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        holidayChartButton = new javax.swing.JButton();
        quoteLabel = new javax.swing.JLabel();
        classRoutineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teacherInfoButton.setBackground(new java.awt.Color(153, 255, 153));
        teacherInfoButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        teacherInfoButton.setForeground(new java.awt.Color(204, 0, 0));
        teacherInfoButton.setText("Teacher Info");
        teacherInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherInfoButtonActionPerformed(evt);
            }
        });

        studentInfoButton.setBackground(new java.awt.Color(153, 255, 153));
        studentInfoButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        studentInfoButton.setForeground(new java.awt.Color(204, 0, 0));
        studentInfoButton.setText("Student Info");
        studentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoButtonActionPerformed(evt);
            }
        });

        bookShopButton.setBackground(new java.awt.Color(153, 255, 153));
        bookShopButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bookShopButton.setForeground(new java.awt.Color(204, 0, 0));
        bookShopButton.setText("Book Shop");
        bookShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookShopButtonActionPerformed(evt);
            }
        });

        libraryButton.setBackground(new java.awt.Color(153, 255, 153));
        libraryButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        libraryButton.setForeground(new java.awt.Color(204, 0, 0));
        libraryButton.setText("Library");
        libraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButtonActionPerformed(evt);
            }
        });

        cantinButton.setBackground(new java.awt.Color(153, 255, 153));
        cantinButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cantinButton.setForeground(new java.awt.Color(204, 0, 0));
        cantinButton.setText("Cantin");
        cantinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantinButtonActionPerformed(evt);
            }
        });

        titleLabel.setBackground(new java.awt.Color(255, 204, 204));
        titleLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(175, 5, 73));
        titleLabel.setText("Existing Info");

        backButton.setBackground(new java.awt.Color(255, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        holidayChartButton.setBackground(new java.awt.Color(153, 255, 153));
        holidayChartButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        holidayChartButton.setForeground(new java.awt.Color(204, 0, 0));
        holidayChartButton.setText("Holiday's chart");
        holidayChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holidayChartButtonActionPerformed(evt);
            }
        });

        quoteLabel.setBackground(new java.awt.Color(255, 204, 204));
        quoteLabel.setFont(new java.awt.Font("Vivaldi", 3, 27)); // NOI18N
        quoteLabel.setForeground(new java.awt.Color(0, 0, 204));
        quoteLabel.setText("Controlling over all existing data");

        classRoutineButton.setBackground(new java.awt.Color(153, 255, 153));
        classRoutineButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        classRoutineButton.setForeground(new java.awt.Color(204, 0, 0));
        classRoutineButton.setText("Class Routine");
        classRoutineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoutineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 200, Short.MAX_VALUE)
                .addComponent(quoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(backButton)
                        .addGap(159, 159, 159)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentInfoButton)
                            .addComponent(teacherInfoButton))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(libraryButton)
                            .addComponent(cantinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(holidayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(classRoutineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holidayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(classRoutineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherInfoButtonActionPerformed
        dispose();
        new TeacherInfoEditable().setVisible(true);
    }//GEN-LAST:event_teacherInfoButtonActionPerformed

    private void studentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoButtonActionPerformed
        dispose();
        new StudentInfoEditable().setVisible(true);
    }//GEN-LAST:event_studentInfoButtonActionPerformed

    private void bookShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookShopButtonActionPerformed
        dispose();
        new BookShopEditable().setVisible(true);
    }//GEN-LAST:event_bookShopButtonActionPerformed

    private void libraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButtonActionPerformed
        dispose();
        new LibraryEditable().setVisible(true);
    }//GEN-LAST:event_libraryButtonActionPerformed

    private void cantinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantinButtonActionPerformed
        dispose();
        new CantinEditable().setVisible(true);
    }//GEN-LAST:event_cantinButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new AdminDashboard().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void holidayChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holidayChartButtonActionPerformed
        dispose();
        new HolidayChartEditable().setVisible(true);
    }//GEN-LAST:event_holidayChartButtonActionPerformed

    private void classRoutineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoutineButtonActionPerformed
        dispose();
        new ClassRoutineEditable().setVisible(true);
    }//GEN-LAST:event_classRoutineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExistingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExistingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExistingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExistingInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExistingInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookShopButton;
    private javax.swing.JButton cantinButton;
    private javax.swing.JButton classRoutineButton;
    private javax.swing.JButton holidayChartButton;
    private javax.swing.JButton libraryButton;
    private javax.swing.JLabel quoteLabel;
    private javax.swing.JButton studentInfoButton;
    private javax.swing.JButton teacherInfoButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
