
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class StudentInfoEditable extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfoEditable
     */
    public StudentInfoEditable() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void display(int val){
        int cnt;
        
        try {
            statement=connect.prepareStatement("select *from studentinfo");
            result=statement.executeQuery();
            ResultSetMetaData resMeta = result.getMetaData();
            
            cnt = resMeta.getColumnCount();
            DefaultTableModel dt= (DefaultTableModel)contentTable.getModel();
            dt.setRowCount(0);
            while(result.next()){
                
                Vector store= new Vector();
                
                for(int i=1; i<=cnt; i++){
                    
                    if(result.getString("class").equals(Integer.toString(val+6))){
                        store.add(result.getString("studentid"));
                        store.add(result.getString("studentname"));
                        store.add(result.getString("studentpassword"));
                        store.add(result.getString("Class"));
                        store.add(result.getString("guardianname"));
                        store.add(result.getString("mobileno"));
                        store.add(result.getString("guardianpassword"));
                    }
                    
                }
                
                if(!store.isEmpty()){
                    dt.addRow(store);
                }
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(StudentInfoEditable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        selectClassLabel = new javax.swing.JLabel();
        selectClassCombobox = new javax.swing.JComboBox<>();
        updateButton = new javax.swing.JButton();
        deletButton = new javax.swing.JButton();
        editStudentNameTextField = new javax.swing.JTextField();
        editGuardianNameTextField = new javax.swing.JTextField();
        editGuardianNameLabel = new javax.swing.JLabel();
        editStudentNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTable = new javax.swing.JTable();
        editStudentPasswordLabel = new javax.swing.JLabel();
        editStudentPasswordTextField = new javax.swing.JTextField();
        editGuardianPhoneNoLabel = new javax.swing.JLabel();
        editGuardianPasswordLabel = new javax.swing.JLabel();
        editGuardianPhoneNoTextField = new javax.swing.JTextField();
        editGuardianPasswordTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setBackground(new java.awt.Color(255, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        titleLabel.setBackground(new java.awt.Color(255, 204, 204));
        titleLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(175, 5, 73));
        titleLabel.setText(" Student's Info");

        selectClassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        selectClassLabel.setText("Select Class:");

        selectClassCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class 6", "Class 7", "Class 8", "Class 9", "Class 10" }));
        selectClassCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClassComboboxActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(153, 255, 153));
        updateButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(204, 0, 0));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deletButton.setBackground(new java.awt.Color(153, 255, 153));
        deletButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deletButton.setForeground(new java.awt.Color(204, 0, 0));
        deletButton.setText("Delete");
        deletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletButtonActionPerformed(evt);
            }
        });

        editGuardianNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editGuardianNameLabel.setText("Edit Guardian Name:");

        editStudentNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editStudentNameLabel.setText("Edit Student Name:");

        contentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID:", "Student Name", "Student Password", "Class", "Guardian Name", "Mobile No", "Guardian Password"
            }
        ));
        contentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contentTable);

        editStudentPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editStudentPasswordLabel.setText("Edit Student Password:");

        editGuardianPhoneNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editGuardianPhoneNoLabel.setText("Edit Guardian Mobile No:");

        editGuardianPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editGuardianPasswordLabel.setText("Edit Guardian Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editStudentNameLabel)
                            .addComponent(editStudentPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(deletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(editStudentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editGuardianPasswordLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(editStudentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editGuardianPhoneNoLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(263, 263, 263)
                                    .addComponent(editGuardianNameLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editGuardianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editGuardianPhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editGuardianPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(backButton)
                        .addGap(257, 257, 257)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectClassCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(selectClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectClassCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGuardianNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGuardianNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGuardianPhoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGuardianPhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGuardianPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGuardianPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        new ExistingInfo().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        
        String studentName = editStudentNameTextField.getText();
        String studentPassword = editStudentPasswordTextField.getText();
        String guardianName = editGuardianNameTextField.getText();
        String guardianPassword = editGuardianPasswordTextField.getText();
        String guardianMobileNo = editGuardianPhoneNoTextField.getText();
        
        try {
            
            statement = connect.prepareStatement("update studentinfo set studentpassword=?, studentName=?, guardianname=? , mobileno=?, guardianpassword=? where studentid=? && Class=?");
            
            String ck = JOptionPane.showInputDialog(this, "Are you sure want to update?\nPress Y for Yes\nPress N for No");
            
            if(ck.equals("Y") || ck.equals("y")){
                statement.setString(1, studentPassword);
                statement.setString(2, studentName);
                statement.setString(3, guardianName);
                statement.setString(4, guardianPassword);
                statement.setString(5, guardianMobileNo);
                statement.setString(6, studentId);
                statement.setString(7, studentClass);

                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated!");
                editStudentNameTextField.setText("");
                editStudentPasswordTextField.setText("");
                editGuardianNameTextField.setText("");
                editGuardianPasswordTextField.setText("");
                editGuardianPhoneNoTextField.setText("");
                display(value);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(StudentInfoEditable.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletButtonActionPerformed
        try {
            
            statement = connect.prepareStatement("delete from studentinfo where studentid=? && Class=?");
            
            String ck = JOptionPane.showInputDialog(this, "Are you sure want to delete?\nPress Y for Yes\nPress N for No");
            
            if(ck.equals("Y") || ck.equals("y")){
                statement.setString(1, studentId);
                statement.setString(2, studentClass);

                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted!");
                
                editStudentNameTextField.setText("");
                editStudentPasswordTextField.setText("");
                editGuardianNameTextField.setText("");
                editGuardianPasswordTextField.setText("");
                editGuardianPhoneNoTextField.setText("");
                display(value);
            }

            
        } catch (SQLException ex) {
            Logger.getLogger(StudentInfoEditable.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deletButtonActionPerformed

    private void selectClassComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClassComboboxActionPerformed
        value = selectClassCombobox.getSelectedIndex();
        display(value);
    }//GEN-LAST:event_selectClassComboboxActionPerformed

    
    private void contentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentTableMouseClicked
        int row = contentTable.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) contentTable.getModel();
        
        studentId = model.getValueAt(row, 0).toString();
        studentClass = model.getValueAt(row, 3).toString();
        
        editStudentNameTextField.setText(model.getValueAt(row, 1).toString());
        editStudentPasswordTextField.setText(model.getValueAt(row, 2).toString());
        editGuardianNameTextField.setText(model.getValueAt(row, 4).toString());
        editGuardianPhoneNoTextField.setText(model.getValueAt(row, 5).toString());
        editGuardianPasswordTextField.setText(model.getValueAt(row, 6).toString());
        
    }//GEN-LAST:event_contentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfoEditable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfoEditable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfoEditable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfoEditable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfoEditable().setVisible(true);
            }
        });
    }
    
    ///custom variables.
    SQL objStudentInfo = new SQL();
    
    Connection connect = objStudentInfo.connection();
    
    PreparedStatement statement;
    ResultSet result;
    private String studentId,studentClass;
    private int value;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable contentTable;
    private javax.swing.JButton deletButton;
    private javax.swing.JLabel editGuardianNameLabel;
    private javax.swing.JTextField editGuardianNameTextField;
    private javax.swing.JLabel editGuardianPasswordLabel;
    private javax.swing.JTextField editGuardianPasswordTextField;
    private javax.swing.JLabel editGuardianPhoneNoLabel;
    private javax.swing.JTextField editGuardianPhoneNoTextField;
    private javax.swing.JLabel editStudentNameLabel;
    private javax.swing.JTextField editStudentNameTextField;
    private javax.swing.JLabel editStudentPasswordLabel;
    private javax.swing.JTextField editStudentPasswordTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectClassCombobox;
    private javax.swing.JLabel selectClassLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
