
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasibul
 */
public class TeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TeacherDashboard
     */
    public TeacherDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        studentInfoButton = new javax.swing.JButton();
        libraryButton = new javax.swing.JButton();
        bookShopButton = new javax.swing.JButton();
        cantinButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        salaryButton = new javax.swing.JButton();
        holidayChartButton = new javax.swing.JButton();
        publishResultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setBackground(new java.awt.Color(255, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        studentInfoButton.setBackground(new java.awt.Color(153, 255, 153));
        studentInfoButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        studentInfoButton.setForeground(new java.awt.Color(204, 0, 0));
        studentInfoButton.setText("Student Info");
        studentInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoButtonActionPerformed(evt);
            }
        });

        libraryButton.setBackground(new java.awt.Color(153, 255, 153));
        libraryButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        libraryButton.setForeground(new java.awt.Color(204, 0, 0));
        libraryButton.setText("Library");
        libraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButtonActionPerformed(evt);
            }
        });

        bookShopButton.setBackground(new java.awt.Color(153, 255, 153));
        bookShopButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bookShopButton.setForeground(new java.awt.Color(204, 0, 0));
        bookShopButton.setText("Book Shop");
        bookShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookShopButtonActionPerformed(evt);
            }
        });

        cantinButton.setBackground(new java.awt.Color(153, 255, 153));
        cantinButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cantinButton.setForeground(new java.awt.Color(204, 0, 0));
        cantinButton.setText("Cantin");
        cantinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantinButtonActionPerformed(evt);
            }
        });

        titleLabel.setBackground(new java.awt.Color(255, 204, 204));
        titleLabel.setFont(new java.awt.Font("Vivaldi", 1, 28)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 255));
        titleLabel.setText("Be the better version of youself!");

        salaryButton.setBackground(new java.awt.Color(153, 255, 153));
        salaryButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        salaryButton.setForeground(new java.awt.Color(204, 0, 0));
        salaryButton.setText("Salary");
        salaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryButtonActionPerformed(evt);
            }
        });

        holidayChartButton.setBackground(new java.awt.Color(153, 255, 153));
        holidayChartButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        holidayChartButton.setForeground(new java.awt.Color(204, 0, 0));
        holidayChartButton.setText("Holiday's chart");
        holidayChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holidayChartButtonActionPerformed(evt);
            }
        });

        publishResultButton.setBackground(new java.awt.Color(153, 255, 153));
        publishResultButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        publishResultButton.setForeground(new java.awt.Color(204, 0, 0));
        publishResultButton.setText("Publish Result");
        publishResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishResultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(studentInfoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(holidayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(libraryButton)
                                .addGap(34, 34, 34)
                                .addComponent(bookShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(publishResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(cantinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(salaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(backButton)
                .addGap(5, 5, 5)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(studentInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookShopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(holidayChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(salaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(publishResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButtonActionPerformed
        dispose();
        Library tch = new Library();
        
        tch.setWhoCall("Teacher");
        tch.setVisible(true);
    }//GEN-LAST:event_libraryButtonActionPerformed

    private void cantinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantinButtonActionPerformed
        dispose();
        Cantin obj = new Cantin();
        obj.setDecision("Teacher");
        obj.setVisible(true);
    }//GEN-LAST:event_cantinButtonActionPerformed

    private void holidayChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holidayChartButtonActionPerformed
        dispose();
        
        HolidayChart obj = new HolidayChart();
        
        obj.setDecision("Teacher");
        obj.setVisible(true);
    }//GEN-LAST:event_holidayChartButtonActionPerformed

    private void bookShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookShopButtonActionPerformed
        dispose();
        BookShop obj = new BookShop();
        obj.setDecision("Teacher");
        obj.setVisible(true);
    }//GEN-LAST:event_bookShopButtonActionPerformed

    private void studentInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoButtonActionPerformed
        dispose();
        new StudentInfo().setVisible(true);
    }//GEN-LAST:event_studentInfoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        String value = JOptionPane.showInputDialog("Do you want to Log out?\nPress y to yes\nPress n to no");
        if(value.equals("y") || value.equals("Y")){
            dispose();
            new HomePage().setVisible(true);
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void salaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Sorry, we get trouble to implement the Payment Gateway System,\nDue to internet problem and resourses\n,Hope we can add this soon!\n");
    }//GEN-LAST:event_salaryButtonActionPerformed

    private void publishResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishResultButtonActionPerformed
        dispose();
        ResultEditable obj = new ResultEditable();
        
        obj.setWhoCall("Teacher");
        obj.setVisible(true);
    }//GEN-LAST:event_publishResultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookShopButton;
    private javax.swing.JButton cantinButton;
    private javax.swing.JButton holidayChartButton;
    private javax.swing.JButton libraryButton;
    private javax.swing.JButton publishResultButton;
    private javax.swing.JButton salaryButton;
    private javax.swing.JButton studentInfoButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
